spring.application.name=sound_bank

spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://localhost:3306/sound_bank
spring.datasource.username=root
spring.datasource.password=tiger

spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8081

mybatis.mapper-locations=mappers/**/*.xml
mybatis.configuration.map-underscore-to-camel-case=false
mybatis.type-aliases-package=com.boot.sound.jwt.mappers

spring.datasource.hikari.max-lifetime=300000
spring.profiles.include=API-KEY


#spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
#spring.datasource.url=jdbc:mariadb://15.165.57.30:3306/sound_bank
#spring.datasource.username=admin
#spring.datasource.password=soundbank18


