spring.application.name=sound_bank

spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://soundbank.c70caqkiqrzd.ap-northeast-2.rds.amazonaws.com:3306/soundbank
spring.datasource.username=admin
spring.datasource.password=soundbank18

# http port number(default 8080)
server.port=8081

# MyBatis - spring(dataSource-config.xml)
mybatis.mapper-locations=mappers/**/*.xml
# mybatis.type-aliases-package=com.example.springBoot_basic_ict04.dao
# Ã¬Â£Â¼Ã¬ÂÂ : falseÃ«Â¥Â¼ Ã¬Â£Â¼Ã«Â©Â´ ÃªÂ°ÂÃ¬Â ÂÃ«Â³ÂÃ­ÂÂÃ¬ÂÂ Ã«Â§ÂÃ«ÂÂÃ«ÂÂ¤.
mybatis.configuration.map-underscore-to-camel-case=false
logging.level.com.atoz_develop.mybatissample.repository=TRACE
mybatis.type-aliases-package=com.boot.sound.jwt.mappers

spring.profiles.include=API-KEY

spring.datasource.hikari.max-lifetime=300000