spring.application.name=sound_bank

#spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
#spring.datasource.url=jdbc:mariadb://15.165.57.30:3306/sound_bank
#spring.datasource.username=admin
#spring.datasource.password=soundbank18
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://localhost:3306/SOUNDBANK
spring.datasource.username=SOUNDBANK
spring.datasource.password=SB18

# http port number(default 8080)
server.port=8081

# MyBatis - spring(dataSource-config.xml)
mybatis.mapper-locations=mappers/**/*.xml
# mybatis.type-aliases-package=com.example.springBoot_basic_ict04.dao
# ì£¼ì : falseë¥¼ ì£¼ë©´ ê°ì ë³íì ë§ëë¤.
mybatis.configuration.map-underscore-to-camel-case=false
logging.level.com.atoz_develop.mybatissample.repository=TRACE
#mybatis.type-aliases-package=com.boot.sound.jwt.mappers
mybatis.type-aliases-package=com.boot.sound.deposit.dto

spring.profiles.include=API-KEY

spring.datasource.hikari.max-lifetime=300000