input {
  jdbc {
    jdbc_driver_library => "/usr/share/logstash/drivers/mariadb-java-client-3.1.4.jar"
    jdbc_driver_class => "org.mariadb.jdbc.Driver"
    jdbc_connection_string => "jdbc:mariadb://soundbank.c70caqkiqrzd.ap-northeast-2.rds.amazonaws.com:3306/soundbank"
    jdbc_user => "admin"
    jdbc_password => "soundbank18"
    statement => "SELECT * FROM exchange_transaction WHERE exchange_transaction_id > :sql_last_value"
    schedule => "* * * * *"
    jdbc_default_timezone => "Asia/Seoul"
    jdbc_paging_enabled => false
    jdbc_page_size => 1000
    use_column_value => true
    tracking_column => "exchange_transaction_id"
    record_last_run => true
    last_run_metadata_path => "/usr/share/logstash/.logstash_exchange_last_run"
    connection_timeout => 15
    jdbc_validation_timeout => 10
  }
}

filter {
  mutate {
    rename => {
      "EXCHANGE_TRANSACTION_ID" => "exchange_transaction_id"
      "CUSTOMER_ID" => "customer_id"
      "FROM_CURRENCY" => "from_currency"
      "TO_CURRENCY" => "to_currency"
      "WITHDRAW_ACCOUNT_NUMBER" => "withdraw_account_number"
      "REQUEST_AMOUNT" => "request_amount"
      "EXCHANGED_AMOUNT" => "exchanged_amount"
      "EXCHANGE_RATE" => "exchange_rate"
      "EXCHANGE_TRANSACTION_DATE" => "exchange_transaction_date"
      "CURRENCY_CODE" => "currency_code"
      "BASE_DATE" => "base_date"
      "TRANSACTION_TYPE" => "transaction_type"
      "APPROVAL_STATUS" => "approval_status"
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://localhost:9200"]
    index => "exchange_transaction_raw"
    document_id => "%{exchange_transaction_id}"
  }
  stdout {
    codec => json_lines
  }
}
